/////////////////////////////////////////////////////////////////////////////
// Name:        src/wasm/apptraits.cpp
// Author:      Hugo Armando Castellanos Morales
// Copyright:   (c) 2022-2026 Hugo Armando Castellanos Morales
// Licence:     wxWindows licence
/////////////////////////////////////////////////////////////////////////////

// For compilers that support precompilation, includes "wx.h".
#include "wx/wxprec.h"

#include "wx/apptrait.h"
#include "wx/stdpaths.h"
#include "wx/evtloop.h"

#include "wx/timer.h"
#include "wx/wasm/timer.h"

#include <emscripten/version.h>     // __EMSCRIPTEN_major__/minor__/tiny__

wxEventLoopBase *wxGUIAppTraits::CreateEventLoop()
{
    return new wxEventLoop();
}

#if wxUSE_TIMER
wxTimerImpl *wxGUIAppTraits::CreateTimerImpl(wxTimer *timer)
{
    return new wxWasmTimerImpl(timer);
}
#endif

wxPortId wxGUIAppTraits::GetToolkitVersion(int *majVer,
                                           int *minVer,
                                           int *microVer) const
{
    // The "toolkit" of this port is Emscripten itself. Unlike GTK or Qt there
    // is no shared runtime library that could differ from the compile-time
    // version: the Emscripten runtime (JS glue code) is generated by the very
    // same compiler version, so both the compile-time and the runtime
    // versions are given by the __EMSCRIPTEN_*__ macros.
    if ( majVer )
        *majVer = __EMSCRIPTEN_major__;
    if ( minVer )
        *minVer = __EMSCRIPTEN_minor__;
    if ( microVer )
        *microVer = __EMSCRIPTEN_tiny__;

    return wxPORT_WASM;
}

wxString wxGUIAppTraits::GetDesktopEnvironment() const
{
    // There is no desktop environment ("KDE", "GNOME", ...) in the browser.
    return wxEmptyString;
}

int wxGUIAppTraits::WaitForChild(wxExecuteData& WXUNUSED(execData))
{
    // Browsers can't spawn child processes: although src/unix/utilsunx.cpp
    // (with wxExecute) is compiled into this port, Emscripten's fork() is a
    // stub that always fails at runtime, so there is never a child process
    // to wait for. Return -1 (error), as the other ports do when waiting
    // fails.
    return -1;
}
